__version__      = '1.4.1'
__author__       = 'Mike Kroutikov'
__author_email__ = 'pgmmpk@gmail.com'
__description__  = 'Church Slavonic extensions to Markdown'
__keywords__     = 'church slavonic, markdown'
__url__          = 'https://github.com/slavonic/cumd/'
